// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelWpf.Data;

namespace ModelWpf.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    partial class ModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModelWpf.Data.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client")
                        .IsRequired();

                    b.Property<string>("Comments");

                    b.Property<int>("DurationDays");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<int>("NumModels");

                    b.Property<bool>("Planned");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("ModelWpf.Data.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Comments");

                    b.Property<string>("HairColor")
                        .IsRequired();

                    b.Property<int>("Height");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("ModelWpf.Data.Model_Assignment", b =>
                {
                    b.Property<int>("AssignmentId");

                    b.Property<int>("ModelId");

                    b.HasKey("AssignmentId", "ModelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Model_Assignments");
                });

            modelBuilder.Entity("ModelWpf.Data.Model_Assignment", b =>
                {
                    b.HasOne("ModelWpf.Data.Assignment", "Assignment")
                        .WithMany("Model_Assignments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ModelWpf.Data.Model", "Model")
                        .WithMany("Model_Assignments")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
